language: node_js
node_js: node
services: mongodb
env:
  global:
    secure: B9DstEag+9wLhsIaCtRpczOeDqvU+dGNFvqyAvIAj8PCU7TxxWSdB17D+CNCcStXPwAJb5Q9RilEmgmtnrB2qcTymUkPnuX3ZBpJf3jT3X8H/gW8TVHa940eDo7XatbvR77EtigvauTvyGh4oM59SxtacG0DYN1MIu5rVhSCHUkV1FzpGF9HZbsXEw7+CQR88kfiRcJvcVrLTRSCylBq2t90ze3JYKbemceu12HE9s4nCgqNqpjB6Zic9ONGkeLkyTLKlKd0CR/y/wJvoh03YmPK3PbXHIJFK0Ifvjci8CrcnyKDntMm4E/1lsH+OsYkXrTwnNJaBFqM2La4k7bUFnVQmY41j3XAfuGirh+DX8F520dqeZgzOug5o3yxKXEY5Z/AC4dR19cvMxmQy68THr0tLjjspcUVlqm1cc8Wjn0kMXRrntFSnXBjEZPC+pfBNKtPShsff18ffdWl5mj1+5J0pCCMFii35+QmOGJGXfvw03UaWe3ScCbYkHkeaCPOjXeY2Lz/x4oAt/MrzcDk79RtDx/kdzXkJtiEen78m0I85U9DFvP9AEEUeqM6cdRqYEuE241OxBIiklJW6yZ0Nac8+o9Y39I1Y1nknJNMpOaH2GPiPVo6LPdMm5lWneH33msATkkUa3DhJoG1Pf28z9TvAVtDYMWx5wxNGmkmdI8=
